---
title: "Fitting a model with a recipe"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Fitting a model with a recipe}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```


This vignette aims to exemplify how you can use recipes within a `tidyflow`. The content and analysis is taken directly from the great work of the `tidymodels` team [here](https://www.tidymodels.org/start/recipes/).



```{r }
library(tidymodels)
library(tidyflow)
library(nycflights13)

flight_data <- 
  flights %>% 
  mutate(
    # Convert the arrival delay to a factor
    arr_delay = ifelse(arr_delay >= 30, "late", "on_time"),
    arr_delay = factor(arr_delay),
    # We will use the date (not date-time) in the recipe below
    date = as.Date(time_hour)
  ) %>% 
  # Include the weather data
  inner_join(weather, by = c("origin", "time_hour")) %>% 
  # Only retain the specific columns we will use
  select(dep_time, flight, origin, dest, air_time, distance, 
         carrier, date, arr_delay, time_hour) %>% 
  # Exclude missing data
  na.omit() %>% 
  # For creating models, it is better to have qualitative columns
  # encoded as factors (instead of character strings)
  mutate_if(is.character, as.factor)

flight_rec <-
  ~ recipe(arr_delay ~ ., data = .x) %>% 
  update_role(flight, time_hour, new_role = "ID") %>% 
  step_date(date, features = c("dow", "month")) %>% 
  step_holiday(date, holidays = timeDate::listHolidays("US")) %>% 
  step_rm(date) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors())

tflow <-
  flight_data %>%
  tidyflow(seed = 555) %>%
  plug_split(initial_split, prop = 3/4) %>%
  plug_recipe(flight_rec) %>%
  plug_model(logistic_reg() %>% set_engine("glm"))

flights_fit <- fit(tflow)

flights_fit %>% 
  pull_tflow_fit() %>% 
  tidy()

flights_fit %>%
  predict_testing(type = "prob") %>%
  roc_curve(truth = arr_delay, .pred_late) %>% 
  autoplot()


```


```{r}
library(tidymodels) # for the rsample package, along with the rest of tidymodels
library(tidyflow)
library(modeldata)  # for the cells data

data(cells, package = "modeldata")

rf_mod <- 
  rand_forest(trees = 1000) %>% 
  set_engine("ranger") %>% 
  set_mode("classification")

rf_fit <-
  cells %>%
  tidyflow(seed = 123) %>%
  plug_split(initial_split, strata = "class") %>%
  plug_formula(class ~ .) %>% 
  plug_model(rf_mod) %>%
  fit()

rf_fit_pred <-
  bind_cols(
    predict_training(rf_fit, type = "prob"), # probabilities
    predict(rf_fit, pull_tflow_training(rf_fit)) # class predictions
  )

rf_fit_pred %>%
  roc_auc(truth = class, .pred_PS)

rf_fit_pred %>%
  accuracy(truth = class, .pred_class)

rf_fit_pred <-
  bind_cols(
    predict_testing(rf_fit, type = "prob"), # probabilities
    predict(rf_fit, pull_tflow_testing(rf_fit)) # class predictions
  )

rf_fit_pred %>%
  roc_auc(truth = class, .pred_PS)

rf_fit_pred %>%
  accuracy(truth = class, .pred_class)

rf_fit_rs <-
  rf_fit %>%
  plug_resample(vfold_cv, v = 10) %>%
  fit()

```

```{r }
library(tidymodels)  # for the tune package, along with the rest of tidymodels
library(tidyflow)
library(modeldata)   # for the cells data
library(vip)         # for variable importance plots

data(cells, package = "modeldata")
cells

tune_spec <- 
  decision_tree(
    cost_complexity = tune(),
    tree_depth = tune()
  ) %>% 
  set_engine("rpart") %>% 
  set_mode("classification")

tflow <-
  cells %>%
  tidyflow(seed = 123) %>%
  plug_formula(class ~ .) %>% 
  plug_split(initial_split, strata = "class") %>%
  plug_resample(vfold_cv) %>%
  plug_grid(grid_regular, levels = 5) %>%
  plug_model(tune_spec)

tree_fit <- fit(tflow)
tree_res <- pull_tflow_fit_tuning(tree_fit)

tree_res %>%
  collect_metrics()

tree_res %>%
  collect_metrics() %>%
  mutate(tree_depth = factor(tree_depth)) %>%
  ggplot(aes(cost_complexity, mean, color = tree_depth)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) +
  scale_x_log10(labels = scales::label_number()) +
  scale_color_viridis_d(option = "plasma", begin = .9, end = 0)

tree_res %>%
  show_best("roc_auc")

final_wf <-  tree_fit %>% complete_tflow(metric = "roc_auc")

final_wf %>% pull_tflow_fit()

final_wf %>% 
  pull_tflow_fit() %>% 
  vip()

final_wf %>%
  predict_testing(type = "prob") %>%
  roc_curve(class, .pred_PS) %>%
  autoplot()
```


```{r}
library(tidymodels)
library(tidyflow)
library(readr)       # for importing data
library(vip)         # for variable importance plots
library(readr)

hotels <- 
  read_csv('https://tidymodels.org/start/case-study/hotels.csv') %>%
  mutate_if(is.character, as.factor) 

dim(hotels)
#> [1] 50000    23

lr_mod <- 
  logistic_reg(penalty = tune(), mixture = 1) %>% 
  set_engine("glmnet")

holidays <- c("AllSouls", "AshWednesday", "ChristmasEve", "Easter", 
              "ChristmasDay", "GoodFriday", "NewYearsDay", "PalmSunday")

lr_recipe <- 
  ~ recipe(children ~ ., data = .x) %>% 
  step_date(arrival_date) %>% 
  step_holiday(arrival_date, holidays = holidays) %>% 
  step_rm(arrival_date) %>% 
  step_dummy(all_nominal(), -all_outcomes()) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors())

tflow <-
  hotels %>%
  tidyflow(seed = 123) %>%
  plug_split(initial_split, strata = "children") %>%
  plug_resample(validation_split, strata = "children", prop = 0.8) %>%
  plug_recipe(lr_recipe) %>%
  plug_grid(expand.grid, penalty = 10^seq(-4, -1, length.out = 30)) %>% 
  plug_model(lr_mod)

cntrl <- control_tidyflow(control_grid = control_grid(save_pred = TRUE))
p_res <- tflow %>% fit(control = cntrl)

p_res %>%
  pull_tflow_fit_tuning() %>% 
  collect_metrics() %>%
  filter(.metric == "roc_auc") %>% 
  ggplot(aes(x = penalty, y = mean)) + 
  geom_point() + 
  geom_line() + 
  ylab("Area under the ROC Curve") +
  scale_x_log10(labels = scales::label_number())

top_models <-
  p_res %>%
  pull_tflow_fit_tuning() %>% 
  show_best("roc_auc", n = 15) %>% 
  arrange(penalty) 

lr_best <-
  top_models %>%
  slice(12)

lr_auc <-
  p_res %>%
  pull_tflow_fit_tuning() %>% 
  collect_predictions(parameters = lr_best) %>% 
  roc_curve(children, .pred_children) %>% 
  mutate(model = "Logistic Regression")

autoplot(lr_auc)

cores <- parallel::detectCores() - 2

rf_mod <- 
  rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>% 
  set_engine("ranger", num.threads = cores) %>% 
  set_mode("classification")

rf_recipe <- 
  ~ recipe(children ~ ., data = .x) %>% 
    step_date(arrival_date) %>% 
    step_holiday(arrival_date) %>% 
    step_rm(arrival_date) 

tflow <-
  tflow %>%
  replace_recipe(rf_recipe) %>%
  replace_model(rf_mod) %>%
  replace_grid(grid_latin_hypercube, size = 25)

rf_res <- tflow %>% fit(control = cntrl)

rf_res %>%
  pull_tflow_fit_tuning() %>%
  autoplot() +
  ylim(c(0.88, 0.93))


rf_best <- 
  rf_res %>%
  pull_tflow_fit_tuning() %>% 
  select_best(metric = "roc_auc")

rf_auc <- 
  rf_res %>%
  pull_tflow_fit_tuning() %>% 
  collect_predictions(parameters = rf_best) %>% 
  roc_curve(children, .pred_children) %>% 
  mutate(model = "Random Forest")

bind_rows(rf_auc, lr_auc) %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity, col = model)) + 
  geom_path(lwd = 1.5, alpha = 0.8) +
  geom_abline(lty = 3) + 
  coord_equal() + 
  scale_color_viridis_d(option = "plasma", end = .6)


final_res <-
  rf_res %>%
  complete_tflow(metric = "roc_auc")

final_res %>%
  predict_testing(type = "prob") %>%
  roc_curve(children, .pred_children) %>%
  autoplot()
```
