on:
  push:
    branches:
      - master
    paths:
      - README.Rmd
    schedule:
      # * is a special character in YAML so you have to quote this string
      - cron: "0 4 * * *"


name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages(c("rmarkdown", "remotes", "devtools")); remotes::install_deps(dependencies = TRUE); devtools::install()'
      - name: Render README
        run: Rscript -e 'options(crayon.enabled = FALSE); rmarkdown::render("README.Rmd")'
      - name: Commit results
        run: |
          git pull origin master
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

